### ISSUE TITLE
Build the Navbar

### ISSUE THREAD

**Issue by SSPENELOPE** [tlg-23-10-sde-4/23-10-JavaScriptProject-Team1-Frontend#2]
- We need to build a Navbar component that can be conditionally rendered onto pages across the application
 - We can use bootstrap or any other tools necessary
 
Priority to be held off on but will need to be added: 
- Implement logic to conditionally show specified nav links based upon a users login status

**Comment by jaytaylor-dev** [comment]
![Image](https://github.com/tlg-23-10-sde-4/23-10-JavaScriptProject-Team1-Frontend/assets/63943804/eef85a26-5fe5-4855-83d3-e19d545ab4a4)
